MxOnline/urls.py
from django.conf.urls import url,include
from django.views.generic import TemplateView
import xadmin
from django.views.static import serve
from MxOnline import settings

from users.views import userLogin,LoginView,RegisterView,ActiveUserView,ForgetPasswordView,ResetView,ModifyPwdView,IndexView
from organizations.views import OrgView
urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',IndexView.as_view(),name="index"),
    url(r'^login/$',LoginView.as_view(),name="login"),
    url(r'register/$',RegisterView.as_view(),name="register"),
    url(r'^captcha/', include('captcha.urls')),
    url(r'active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name="userActive"),
    url(r'^forget/$',ForgetPasswordView.as_view(),name="forgetpwd"),
    url(r'reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset"),
    url(r'modifypwd/$',ModifyPwdView.as_view(),name="modifypwd"),
    url(r'^org/',include('organizations.urls',namespace='org')),
    url(r'^media/(?P<path>.*)$',serve,{"document_root":settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$',serve,{"document_root":settings.STATIC_ROOT}),
    url(r'^course/',include('courses.urls',namespace="course")),
    url(r'^users/',include('users.urls',namespace="users"))


]
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/courses/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'Clarence'
__date__ = '2017/4/21 9:06'

from django.conf.urls import url
from .views import CourseListView,CourseDetailView,CourseInfoView,CourseCommentView,AddCourseCommentsView



urlpatterns = [
    url(r'^list/$',CourseListView.as_view(),name="courseList"),
    url(r'detail/(?P<course_id>\d+)/$',CourseDetailView.as_view(),name="courseDetail"),
    url(r'info/(?P<course_id>\d+)/$',CourseInfoView.as_view(),name="CourseInfo"),
    url(r'comment/(?P<course_id>\d+)/$',CourseCommentView.as_view(),name="CourseComment"),
    url(r'^add_comment/$', AddCourseCommentsView.as_view(), name="addCourseComment")

    # url(r'^add_ask/$',AddUserAskView.as_view(),name="addUserAsk"),
    # url(r'^home/(?P<org_id>\d+)/$',OrgHomeView.as_view(),name="home"),
    # url(r'^course/(?P<org_id>\d+)/$',OrgCourseView.as_view(),name="orgCourse"),
    # url(r'^desc/(?P<org_id>\d+)/$',OrgDescView.as_view(),name="orgDesc"),
    # url(r'^orgteacher/(?P<org_id>\d+)/$',OrgTeacherView.as_view(),name="orgTeacher"),
    # url(r'^add_fav/$',AddFavouriteView.as_view(),name="addFav")



]

apps/organizations/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'Clarence'
__date__ = '2017/4/18 15:11'

from django.conf.urls import url,include

from .views import OrgView,AddUserAskView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,AddFavouriteView
from .views import TeacherListView,TeacherDetailView
urlpatterns = [
    url(r'^list/$',OrgView.as_view(),name="orgList"),
    url(r'^add_ask/$',AddUserAskView.as_view(),name="addUserAsk"),
    url(r'^home/(?P<org_id>\d+)/$',OrgHomeView.as_view(),name="home"),
    url(r'^course/(?P<org_id>\d+)/$',OrgCourseView.as_view(),name="orgCourse"),
    url(r'^desc/(?P<org_id>\d+)/$',OrgDescView.as_view(),name="orgDesc"),
    url(r'^orgteacher/(?P<org_id>\d+)/$',OrgTeacherView.as_view(),name="orgTeacher"),
    url(r'^add_fav/$',AddFavouriteView.as_view(),name="addFav"),
    url(r'^teacher/list/$',TeacherListView.as_view(),name="teacherList"),
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$',TeacherDetailView.as_view(),name="teacherDetail"),



]

apps/users/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'Clarence'
__date__ = '2017/5/8 14:46'
from django.conf.urls import url,include
from .views import UserInfoView,UploadImageView,UpdatePwdView,SendEmailCodeView,UserCourseView,UserFavOrgView
from .views import UserFavTeachersView,UserFavCourseView,UserMessageView,LogoutView

urlpatterns = [
    url(r'^info/$',UserInfoView.as_view(),name="userInfo"),
    url(r'^imageUpload/$',UploadImageView.as_view(),name="uploadImage"),
    url(r'^update/pwd/$',UpdatePwdView.as_view(),name="updatePwd"),
    url(r'^sendEmailCode/$',SendEmailCodeView.as_view(),name="sendEamil"),
    # url(r'^updateUserEmail/$',)
    url(r'^userCourse/$',UserCourseView.as_view(),name="userCourse"),
    url(r'userFavOrg/$',UserFavOrgView.as_view(),name="userFavOrg"),
    url(r'^userFavTeacher/$',UserFavTeachersView.as_view(),name="userFavTeacher"),
    url(r'^userFavCourse/$',UserFavCourseView.as_view(),name="userFavCourse"),
    url(r'^userMessage/$',UserMessageView.as_view(),name="userMessage"),
    url(r'^logout/$',LogoutView.as_view(),name="logout")


]

extra_apps/xadmin/views/base.py
import sys
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
if sys.version_info.major < 3:
  from django.utils.encoding import force_unicode as force_text
  from django.utils.encoding import smart_unicode as smart_text
else:
  from django.utils.encoding import force_text
  from django.utils.encoding import smart_text
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils.datastructures import SortedDict
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from xadmin.util import static, json, vendor, sortkeypicker


csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)
            new_context = context_class(_dict, **{
                'autoescape': context.autoescape,
                'current_app': context.current_app,
                'use_l10n': context.use_l10n,
                'use_tz': context.use_tz,
            })
            new_context['admin_view'] = context['admin_view']
            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                new_context['csrf_token'] = csrf_token
            nodes.append(t.render(new_context))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in list(p):
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in list(p):
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context, current_app=self.admin_site.name)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

    def init_request(self, *args, **kwargs):
        pass

    def init_plugin(self, *args, **kwargs):
        plugins = []
        for p in self.base_plugins:
            p.request = self.request
            p.user = self.user
            p.args = self.args
            p.kwargs = self.kwargs
            result = p.init_request(*args, **kwargs)
            if result is not False:
                plugins.append(p)
        self.plugins = plugins

    @filter_hook
    def get_context(self):

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modifypwd' %}" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" value="{{ email }}" name="email">
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="submit" value="提交" >
                </li>
            </ul>
            {% csrf_token %}
        </form>

    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="{% static 'images/check2.png' %}">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/reset_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>未找到对应用户</p>
</body>
</html>

templates/user-center-base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
  <meta charset="UTF-8">
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <title>{% block title %}个人信息- 慕学在线网{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">

  <link rel="stylesheet" href="{% static 'css/lq.datetimepick.css' %}"/>

  {% block custom_css %}
  {% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
  <header>
    <div class=" header header2">
      <div class="top">
        <div class="wp">
          <div class="fl"><p>服务电话：<b>33333333</b></p></div>
          <!--登录后跳转-->
          {% if request.user.is_authenticated %}
            <div class="personal">
              <dl class="user fr">
                <dd>{{ request.user.nick_name }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
              </dl>
              <div class="userdetail">
                <dl>
                  <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}" /></dt>
                  <dd>
                    <h2>{{ request.user.nick_name }}</h2>
                    <p>{{ request.user.username }}</p>
                  </dd>
                </dl>
                <div class="btn">
                  <a class="personcenter fl" href="{% url 'users:userInfo' %}">进入个人中心</a>
                  <a class="fr" href="{% url 'users:logout' %}">退出</a>
                </div>
              </div>
            </div>
            <a href="{% url 'users:userMessage' %}">
              <div class="msg-num">
                <span id="MsgNum">{{ request.user.unread_nums }}</span>
              </div>
            </a>
          {% else %}
            <a style="color:white" class="fr registerbtn" href="">注册</a>
            <a style="color:white" class="fr loginbtn" href="">登录</a>
          {% endif %}

        </div>
      </div>

      <div class="middle">
        <div class="wp">
          <a href=""><img class="fl" src=""/></a>
          <div class="searchbox fr">
            <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
              <ul class="selectMenu" id="jsSelectMenu">
                <li data-value="course">公开课</li>
                <li data-value="org">课程机构</li>
                <li data-value="teacher">授课老师</li>
              </ul>
            </div>
            <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
            <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
          </div>
        </div>
      </div>


      <nav>
        <div class="nav">
          <div class="wp">
            <ul>
              <li class="{% ifequal request.path '/' %}active{% endifequal %}"><a href="{% url 'index' %}">首页</a></li>
              <li class="{% ifequal request.path|slice:'7' '/course' %}active{% endifequal %}">
                <a href="{% url 'course:courseList' %}">
                  公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                </a>
              </li>
              <li class="{% ifequal request.path|slice:'17' '/org/teacher/list' %}active{% endifequal %}">
                <a href="{% url 'org:teacherList' %}">授课教师</a>
              </li>
              <li class="{% ifequal request.path|slice:'9' '/org/list' %}active{% endifequal %}"><a href="{% url 'org:orgList' %}">授课机构</a></li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </header>
</section>


<!--crumbs start-->
{% block custom_bread %}
<section>
  <div class="wp">
    <ul class="crumbs">
      <li><a href="">首页</a>></li>
      <li><a href="">个人中心</a>></li>
      <li>个人信息</li>
    </ul>
  </div>
</section>
{% endblock %}

<section>
  <div class="wp list personal_list">
    <div class="left">
      <ul>
        <li class="active2"><a href="">个人资料</a></li>
        <li><a href="{% url 'users:userCourse' %}">我的课程</a></li>
        <li><a href="{% url 'users:userFavOrg' %}">我的收藏</a></li>
        <li>
          <a href="{% url 'users:userMessage' %}" style="position: relative;">
            我的消息
          </a>
        </li>
      </ul>
    </div>

    {% block right_content %}


    {% endblock %}

  </div>
</section>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}"></script>
<script src="{% static 'js/unslider.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"></script>
<script src="{% static 'js/validateDialog.js' %}"></script>
<script src="{% static 'js/deco-common.js' %}"></script>

<script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
<script src="{% static 'js/validate.js' %}"></script>
<script src="{% static 'js/deco-user.js' %}"></script>

{% block custom_js %}
{% endblock %}

<script>
  // 课程取消收藏
  $('.jsDeleteFav_course').on('click', function () {
    var _this = $(this),
      favid = _this.attr('data-favid');
    $.ajax({
      cache: false,
      type: "POST",
      url: "",
      data: {
        fav_type: 1,
        fav_id: favid,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      async: true,
      success: function (data) {
        Dml.fun.winReload();
      }
    });
  });
  $('.jsDeleteFav_teacher').on('click', function () {
    var _this = $(this),
      favid = _this.attr('data-favid');
    $.ajax({
      cache: false,
      type: "POST",
      url: "",
      data: {
        fav_type: 3,
        fav_id: favid,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      async: true,
      success: function (data) {
        Dml.fun.winReload();
      }
    });
  });
  $('.jsDeleteFav_org').on('click', function () {
    var _this = $(this),
      favid = _this.attr('data-favid');
    $.ajax({
      cache: false,
      type: "POST",
      url: "",
      data: {
        fav_type: 2,
        fav_id: favid,
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      async: true,
      success: function (data) {
        Dml.fun.winReload();
      }
    });
  });
</script>


<script>
  var shareUrl = '',
    shareText = '',
    shareDesc = '',
    shareComment = '';
  $(function () {
    $(".bdsharebuttonbox a").mouseover(function () {
      var type = $(this).attr('data-cmd'),
        $parent = $(this).parent('.bdsharebuttonbox'),
        fxurl = $parent.attr('data-url'),
        fxtext = $parent.attr('data-text'),
        fxdesc = $parent.attr('data-desc'),
        fxcomment = $parent.attr('data-comment');
      switch (type) {
        case 'tsina':
        case 'tqq':
        case 'renren':
          shareUrl = fxurl;
          shareText = fxdesc;
          shareDesc = '';
          shareComment = '';
          break;
        default :
          shareUrl = fxurl;
          shareText = fxtext;
          shareDesc = fxdesc;
          shareComment = fxcomment;
          break;
      }
    });
  });
  function SetShareUrl(cmd, config) {
    if (shareUrl) {
      config.bdUrl = "" + shareUrl;
    }
    if (shareText) {
      config.bdText = shareText;
    }
    if (shareDesc) {
      config.bdDesc = shareDesc;
    }
    if (shareComment) {
      config.bdComment = shareComment;
    }
    return config;
  }
  window._bd_share_config = {
    "common": {
      "onBeforeClick": SetShareUrl,
      "bdPic": "",
      "bdMini": "2",
      "searchPic": "1",
      "bdMiniList": false
    },
    "share": {
      "bdSize": "16"
    }
  };
  with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com{% static '' %}api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];
</script>
</body>
</html>

templates/usercenter-fav-course.html
{% extends 'user-center-base.html' %}
{% load staticfiles %}
{% block title %}我收藏的课程 {% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我收藏的课程</li>
            </ul>
        </div>
    </section>{% endblock %}
{% block right_content %}
        <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:userFavOrg' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:userFavTeacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:userFavCourse' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in favCourses %}
                        <div class="module1_5 box">
                            <a href="course-detail.html">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                            </div>
                        </div>
                        {% endfor %}



                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'user-center-base.html' %}
{% load staticfiles %}
{% block title %}我收藏的课程机构 {% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>我收藏的课程机构</li>
            </ul>
        </div>
    </section>{% endblock %}
{% block right_content %}
    <div class="right">
      <div class="personal_des Releasecont">
        <div class="head">
          <h1>我的收藏</h1>
        </div>

      </div>
      <div class="personal_des permessage">
        <div class="head">
          <ul class="tab_header messagehead">
            <li class="active"><a href="{% url 'users:userFavOrg' %}">课程机构</a></li>
            <li><a href="{% url 'users:userFavTeacher' %}">授课教师 </a></li>
            <li><a href="{% url 'users:userFavCourse' %}">公开课程</a></li>
          </ul>
        </div>
        <div class="messagelist">
          {% for org in org_list %}
          <div class="messages butler_list company company-fav-box">
            <dl class="des fr">
              <dt>
                <a href="{% url 'org:home' org.id %}">
                  <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                </a>
              </dt>
              <dd>
                <h1><a href="{% url 'org:home' org.id %}">{{ org.name }}</a></h1>
                <div class="pic fl" style="width:auto;">
                  <img src="{% static 'images/authentication.png' %}"/>
                  <img src="{% static 'images/gold.png' %}"/>
                </div>
                <span class="c8 clear">{{ org.address }}</span>
                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
              </dd>
            </dl>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock %}